### ISSUE TITLE
Linear disturbance features should have width column

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/disturbance_explorer#6]
The width column from the disturbance mapping products should be carried through to the Shiny app. This could be used for assigning custom buffer widths. For example, buffers could be set to be width*10.

**Comment by prvernier** [comment]
The WIDTH_M column is fairly small compared to the buffer sizes used often in the app e.g., default is 1000m. It would make sense for small widths, maybe 50-100m. Same with multiplier, it migh work with small values, but if you used width*1000, this would lead to huge differences. Maybe we park this one for now.
